### ISSUE TITLE
[BP-2063] Notice: Undefined index: PayPalExpressController.php

### ISSUE THREAD

**Issue by Martje65** [buckaroo-it/WooCommerce#128]
After installing the Buckaroo Woocommerce Payments Plugin we have the next error in wordpress admin.

Notice: Undefined index: express in test.nl/wp-content/plugins/wc-buckaroo-bpe-gateway/controllers/PaypalExpressController.php on line 130

Plugin version  3.4.0
WooCommerce version 6.9.4
WordPress version 6.0.2
PHP version 7.4

**Comment by Buckaroo-Rene** [comment]
Hello @Martje65 ,

Thank you for sharing the issue/notice that you are facing. It is just a notice, so nothing critical.
We'll fix it in one of the upcoming sprints (BP-).
For now you can try the manual steps below which might solve this issue quite quickly.

- Login in your **Wordpress admin**.
- Go to the installed **Buckaroo plugin settings** → click on the "**edit**" button for the **PayPal** payment method.
- Now don't change the settings, but just click on the "**save changes**" button on the bottom of this page.
This might remove the notice that is showed.

Please let me know if this works and removed the notice.

**Comment by Martje65** [comment]
Good morning  @Buckaroo-Rene , that works and has removed the notice.

**Comment by Buckaroo-Rene** [comment]
@Martje65 ,

Thank you for the confirmation. Good to hear that this has solved the issue quickly for you.
