### ISSUE TITLE
Add a hook for other plugins to extend functionality

### ISSUE THREAD

**Issue by ruudvosensetz** [buckaroo-it/WooCommerce#142]
This is more a feature request then an issue.

We are informing our website users when a payment has been made, but we also update a meta inside WordPress that a payment has been made for an order.
We want to hook into the fn_buckaroo_process_response() function but there is nowhere in the plugin hooks to hook in to it.

I will submit a fork for the change which will be simple one extra line to have some more functionality.

**Comment by Buckaroo-Rens** [comment]
@ruudvosensetz Thanks for your first issue. Looking forward to your PR, please we aware of our contribution guidelines.

**Comment by ruudvosensetz** [comment]
> @ruudvosensetz Thanks for your first issue. Looking forward to your PR, please we aware of our contribution guidelines.

https://github.com/buckaroo-it/WooCommerce/pull/143

**Comment by ruudvosensetz** [comment]
Sorry for the inconvinient, but I figured it out in an other way.
