### ISSUE TITLE
BP-3661 Error 404 on blocks.js

### ISSUE THREAD

**Issue by jelle-opencii** [buckaroo-it/WooCommerce#277]
I get a 404 on the loading of blocks.js in the WordPress admin. This issue comes from line 112 of index.php in the root folder. This is the only wp_enqueue_script where plugin_dir_url( __FILE__ ) is not prepended to the file path, Changing this line to
wp_enqueue_script( 'buckaroo-block-script', plugin_dir_url( __FILE__ ) . 'assets/js/dist/blocks.js', array( 'wp-blocks', 'wp-element' ) );
makes it load the file.

**Comment by Buckaroo-Rene** [comment]
Hi @jelle-opencii ,

Thank you for contacting us about the issue that you where facing.
What versions are you using?
  - Buckaroo Plugin
  - Wordpress / WooCommerce version
  - PHP Version

**Comment by jelle-opencii** [comment]
Hi @Buckaroo-Rene 

Buckaroo: 3.13.1
WooCommerce: 9.1.2
WordPress: 6.5.5

**Comment by roesware** [comment]
Same issue here

**Comment by Buckaroo-Rene** [comment]
We scheduled the new release for tomorrow morning containing a fix for this issue.

**Comment by Buckaroo-Rene** [comment]
Resolved in: https://github.com/buckaroo-it/WooCommerce/releases/tag/v3.14.0
