### ISSUE TITLE
BP-3907 Bug in recent browser updates with payment gateway dropdowns

### ISSUE THREAD

**Issue by matthijscremers** [buckaroo-it/WooCommerce#298]
**Issue**
Buckaroo adds div elements around the option elements in its payment gateway template files.

Example of a file where this happens: wc-buckaroo-bpe-gateway\templates\gateways\creditcard.php
![image](https://github.com/user-attachments/assets/1b58cb3e-ba7e-42bb-b1ca-4a0d1a375630)

**The effect of the issue**
In the latest version of Chrome but also in Firefox and Edge, the div elements around the dropdown option elements cause the options to not be included in the select dropdown but instead be shown outside of it which makes them unclickable. The div elements seem to break the select functionality.

**The fix**
The fix for this issue is to remove the div elements from the foreach loop in the individual payment method gateway template .php files. This way there will be just option elements in the select dropdown element. This solves the issue in all browsers.

See screenshot of the changed template file with the fix included in it:
![image](https://github.com/user-attachments/assets/ee04c0ae-c6c2-419f-8c80-001d8f01e115)

**Comment by Buckaroo-Rene** [comment]
Hi @matthijscremers ,

Thank you for informing us about this issue. We are aware of this issue and we are looking into a solution.
We'll keep you posted about the issue in this ticket.

**Comment by Buckaroo-Rene** [comment]
Hi @matthijscremers ,

Thanks again for your time to provide us all the information.
We’d like to inform you that the issue has been addressed, and a fix is now available in version [3.14.1](https://github.com/buckaroo-it/WooCommerce/releases/tag/v3.14.1) of the plugin.
