### ISSUE TITLE
The plugin is not available for download, are there any alternative links?

### ISSUE THREAD

**Issue by mapsi-fixi** [buckaroo-it/WooCommerce#99]
Like in the title, i have to install plugin for my customer, but i cant download it from official wordpress plugin store, any alternative trusted link ?

**Comment by Buckaroo-Rene** [comment]
**@mapsi-fixi,**
Thank you for contacting us.
You can download one of the latest releases from our Github page instead. WordPress offers a way to install plugins with a .ZIP file by uploading them. We are in contact with WordPress about getting the plugin back in the store as soon as possible.
Unfortunately their review process is taking some time.

**You can download the .ZIP file for our plugin version 3.2.2 (LATEST VERSION) with the link below:**
[https://github.com/buckaroo-it/WooCommerce/releases/tag/v3.2.2](https://github.com/buckaroo-it/WooCommerce/releases/tag/v3.2.2)

**Comment by Buckaroo-Rens** [comment]
Fixed.
